#!/bin/sh
echo "RUNNING BLURAY DISC DAEMON ..."
udisksctl monitor | while read -r line
do
    case "$line" in
        *"MediaAvailable:               true"*)
	pgrep -f "/usr/local/bin/blustart" >/dev/null || \
	gnome-terminal --title="Bluray Disc Session Burner" \
    	-- bash -c '/usr/local/bin/blustart; exec bash';;
    esac
done
