#!/bin/sh
DEV=$(lsblk -ndo NAME,TYPE | awk '$2=="rom"{print $1; exit}')
[ -z "$DEV" ] && {
    echo "No optical drive found."
    exit 1
}

echo ""
echo -n "- "
echo -n "Disc Total Free Space: (/dev/$DEV) -> "
dvd+rw-mediainfo /dev/"$DEV" 2>/dev/null | awk '/Free Blocks:/ {
    split($3,a,"*");
    printf "%.2f GiB\n", a[1]*2048/1024/1024/1024
}' | tail -n 1
